### ISSUE TITLE
请问一下怎么用啊

### ISSUE THREAD

**Issue by leafleave** [Srar/189CloudLinkTools#1]
如题

**Comment by Srar** [comment]
http://open.189.cn/ 申请权限 然后把申请到的appKey和appSecret填入`config.json` 然后确保`config.json`内的回调地址和天翼云开放平台的回调地址一致.

当配置完毕后访问`http://你的域名:端口/auth`进行应用授权

**Comment by Srar** [comment]
如问题已经解决 请关闭issue

**Comment by ssnh** [comment]
你好，我试着在vps上搭建，可是始终报错
/data/wwwroot/189/app.js:9
setInterval(() => {
             ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3`
`node -v 显示是 v0.10.46  问下是搭建环境问题还是其他？万分感谢

**Comment by XiaoPika** [comment]
55555555555555

![qq 20171219182645](https://user-images.githubusercontent.com/10910848/34152661-55c42436-e4ea-11e7-9a41-34b313eec352.jpg)
